install.packages(c("dslabs", "ggplot2", "tidyverse", "pdftools", "tidytext", "textdata", "broom"))
library(dslabs)
library(ggplot2)
library(dplyr)
library(tidyr)
library(tidyverse)
library(pdftools)
library(rvest)
library(tidytext)
library(scales)
library(lubridate)
library(broom)